language: java
jdk: oraclejdk7
env:
    matrix:
    - ANDROID_SDKS=android-8            ANDROID_TARGET=android-8   ANDROID_ABI=armeabi      PLATFORM=8
    - ANDROID_SDKS=android-10           ANDROID_TARGET=android-10  ANDROID_ABI=armeabi      PLATFORM=10
    - ANDROID_SDKS=android-16,sysimg-16 ANDROID_TARGET=android-16  ANDROID_ABI=armeabi-v7a  PLATFORM=16
    - ANDROID_SDKS=android-17,sysimg-17 ANDROID_TARGET=android-17  ANDROID_ABI=armeabi-v7a  PLATFORM=17
    - ANDROID_SDKS=android-19,sysimg-19 ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a  PLATFORM=19
before_install:
    # Install base Android SDK
    - sudo apt-get update -qq
    - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
    - wget http://dl.google.com/android/android-sdk_r22.3-linux.tgz
    - tar xzf android-sdk_r22.3-linux.tgz
    - export ANDROID_HOME=$PWD/android-sdk-linux
    - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools

    # install android build tools
    - wget https://dl-ssl.google.com/android/repository/build-tools_r19-linux.zip
    - unzip build-tools_r19-linux.zip -d $ANDROID_HOME
    - mkdir -p $ANDROID_HOME/build-tools/
    - mv $ANDROID_HOME/android-4.4 $ANDROID_HOME/build-tools/19

    # Install required Android components.
    - echo yes | android update sdk --filter platform-tools --no-ui --force > /dev/null
    - echo yes | android update sdk --filter $ANDROID_SDKS --no-ui --force > /dev/null
    - echo yes | android update sdk --filter extra-android-support --no-ui --force > /dev/null
    - echo yes | android update sdk --filter extra-android-m2repository --no-ui --force > /dev/null

    # Create and start emulator
    - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
    - emulator -avd test -no-skin -no-audio -no-window &

before_script:
    # Make sure the emulator has started before running tests
    - chmod +x wait_for_emulator
    - ./wait_for_emulator

install: /bin/true # always succeeds

script: mvn install -Dandroid.device=test -Dandroid.platform=$PLATFORM